### ISSUE TITLE
Graph in EL4 first draft

### ISSUE THREAD

**Issue by AbbyANoble** [TeamBasedInquiryLearning/precalculus#241]
I can't get one of my graphs to look the way it's supposed to. It's 5.4.1 e at line 168 in the file, and pull request #240.

`<image>
              <sageplot>
                f(x) = log(x)/log(2)
                p=point([(.25,-2),(.5,-1),(1,0),(2,1),(4,2)],pointsize=50,color='blue', xmin=-8, xmax=8, ymin=-8, ymax=8)
                p+=line([(0,-9),(0,9)], linestyle="--", color='red',xmin=-8, xmax=8, ymin=-8, ymax=8, thickness=3)
                p+=plot(f, (x, .00001, 9), color='blue', thickness=3, gridlines=[[-8,-7,..,8],[-8,-7,..,8]])
                p
              </sageplot>
            </image>`

is rendering as

![image](https://github.com/TeamBasedInquiryLearning/precalculus/assets/85640990/db9cf023-76c2-4acd-8867-77704ca07c93)

**Comment by siwelwerd** [comment]
I added in an xml:id to the image when merging in #240.  This seems to have fixed it in the Codechat, let's double check in the deployment shortly.

**Comment by siwelwerd** [comment]
@AbbyANoble Please check [Activity 5.4.1(e)](https://teambasedinquirylearning.github.io/precalculus/2024/instructor/EL4.html#activity-exp-graphs-intro-6) and close this if it is now what you intended.

**Comment by AbbyANoble** [comment]
Yep! Weird that that fixed it when I don't think any of my images have xml:id's. 😬

**Comment by siwelwerd** [comment]
>Weird that that fixed it when I don't think any of my images have xml:id's.

I think it has to do with the way that pretext caches images and only rebuilds them when they change.  I think by inserting the xml:id I convinced it that it needed to be regenerated (because the image name is derived from the xml:id).  But see also where we [ran into the same issue in the calculus book](https://github.com/TeamBasedInquiryLearning/calculus/issues/78), and eventually went back and made sure every image had an xml:id.  Best practice is to make sure to put an xml:id on all of your images.

@StevenClontz: Reading back through that other issue, is it possible that https://github.com/PreTeXtBook/pretext-cli/issues/579 wasn't actually fixed and that's what caused Abby's problem above? I am happy to work around here by making sure we always use xml:ids, but if something is still buggy we should report upstream--especially as there is no error generated by this, making it hard for an author to track down.
