### ISSUE TITLE
Checkit Build

### ISSUE THREAD

**Issue by siwelwerd** [TeamBasedInquiryLearning/precalculus#315]
Nothing is building at https://teambasedinquirylearning.github.io/precalculus/2024/exercises in the current Github Action.  I think @TienChih already wrote some exercises for Module PR, so I'd like to make those at least available so we can share with our authors so they don't duplicate effort.

**Comment by StevenClontz** [comment]
There are a lot of chores of this flavor that also need to be done for calculus and LA...

I'm becoming increasingly convinced that we should have a monorepo for the resource library, so everything works the same way across our books. There are a few blockers I can think of offhand to making a reasonable authoring experience within a repo containing multiple pretext projects. Fortunately, I'll be in Tacoma with the #PreTeXtGang next week, so that's probably what I'll attack, with the help of @oscarlevin and others.

**Comment by siwelwerd** [comment]
Yeah, I think it's worth exploring that now that we are looking at having 3 mature books in a few months.  If there is a relatively painless way that we could keep the initial development of a hypothetical future book out of the monorepo during the initial writing, I think that would be ideal (so that the messy development happens in a bit more "private" (not really, but feels that way) setting); and then once it's ready for students, move it in.  Should also ask our authoring team how they feel about that.

I think one important thing to consider is the slowness of the Github actions; this book takes over 20 minutes to run each time.  I'd want to make sure there was a way that merging a commit wouldn't trigger a rebuild of all 3 books, presumably taking an hour to run.

But in the meantime... a workaround so that our authors can see work that's already been done would be most welcome.

**Comment by StevenClontz** [comment]
Oh sure, there's no reason to have initial drafts of new books in the monorepo - that should be done however the "right" way to create a fresh PreTeXt project is done at the time it's created. But once it's in the library, it'd be great to have infrastructure to ensure everything is aligned with each other.

**Comment by StevenClontz** [comment]
> this book takes over 20 minutes to run each time

I think that we should have a way to do a quick local check (maybe just the subset of HTML touched by the edits) for each commit, but then have a full check of the entire book before merging into main. Maybe a `staging` branch could run that full build.
